import type {
  ActivityItem,
  Automation,
  ChatMessage,
  Client,
  Company,
  Deal,
  DocumentItem,
  Invoice,
  Lead,
  Payment,
  Project,
  Quote,
  Task,
  User,
} from "@/types";

export const demoCompany: Company = {
  id: "co_klirline_demo",
  name: "KlirBuild",
  email: "ops@klirline.app",
  phone: "+1 (514) 555-0142",
  website: "https://www.klirline.ca/",
  plan: "growth",
  subscriptionStatus: "trialing",
  enabledModules: ["construction-os", "cleaning-os"],
  brandingPrimary: "#1A365D",
  brandingAccent: "#C4A574",
};

export const demoUser: User = {
  id: "user_admin",
  name: "Alex Rivera",
  email: "alex@klirline.demo",
  role: "COMPANY_ADMIN",
  companyId: demoCompany.id,
  avatarInitials: "AR",
};

export const clients: Client[] = [
  {
    id: "cli_1",
    companyId: demoCompany.id,
    name: "Nordic Facilities Inc.",
    email: "billing@nordicfacilities.com",
    phone: "+1 (416) 555-0198",
    status: "active",
    tags: ["enterprise", "retainer"],
    city: "Toronto",
    industry: "Facilities",
    owner: "Alex Rivera",
    createdAt: "2025-11-12",
    lifetimeValue: 128400,
  },
  {
    id: "cli_2",
    companyId: demoCompany.id,
    name: "Harbour Dental Group",
    email: "admin@harbourdental.ca",
    phone: "+1 (604) 555-0111",
    status: "active",
    tags: ["healthcare", "monthly"],
    city: "Vancouver",
    industry: "Healthcare",
    owner: "Sam Chen",
    createdAt: "2026-01-08",
    lifetimeValue: 46200,
  },
  {
    id: "cli_3",
    companyId: demoCompany.id,
    name: "Lumen Retail Partners",
    email: "ap@lumenretail.com",
    phone: "+1 (514) 555-0177",
    status: "lead",
    tags: ["retail", "outbound"],
    city: "Montreal",
    industry: "Retail",
    owner: "Alex Rivera",
    createdAt: "2026-06-02",
    lifetimeValue: 0,
  },
  {
    id: "cli_4",
    companyId: demoCompany.id,
    name: "Cascade Builders",
    email: "projects@cascadebuilders.ca",
    phone: "+1 (403) 555-0133",
    status: "inactive",
    tags: ["construction"],
    city: "Calgary",
    industry: "Construction",
    owner: "Jordan Lee",
    createdAt: "2025-08-21",
    lifetimeValue: 89100,
  },
];

export const leads: Lead[] = [
  {
    id: "lead_1",
    companyId: demoCompany.id,
    name: "Maple Clinic Network",
    email: "growth@mapleclinic.ca",
    source: "Website",
    status: "qualified",
    score: 82,
    owner: "Sam Chen",
    createdAt: "2026-06-28",
  },
  {
    id: "lead_2",
    companyId: demoCompany.id,
    name: "Orbit Logistics",
    email: "ops@orbitlogistics.io",
    source: "Referral",
    status: "contacted",
    score: 64,
    owner: "Alex Rivera",
    createdAt: "2026-07-01",
  },
  {
    id: "lead_3",
    companyId: demoCompany.id,
    name: "BrightPath Schools",
    email: "it@brightpath.edu",
    source: "Conference",
    status: "new",
    score: 51,
    owner: "Jordan Lee",
    createdAt: "2026-07-05",
  },
];

export const deals: Deal[] = [
  {
    id: "deal_1",
    companyId: demoCompany.id,
    title: "Annual facilities OS",
    clientName: "Nordic Facilities Inc.",
    value: 48000,
    stage: "negotiation",
    owner: "Alex Rivera",
    closeDate: "2026-07-30",
  },
  {
    id: "deal_2",
    companyId: demoCompany.id,
    title: "Clinic rollout (6 sites)",
    clientName: "Harbour Dental Group",
    value: 27600,
    stage: "proposal",
    owner: "Sam Chen",
    closeDate: "2026-08-12",
  },
  {
    id: "deal_3",
    companyId: demoCompany.id,
    title: "Retail pilot",
    clientName: "Lumen Retail Partners",
    value: 12000,
    stage: "qualified",
    owner: "Alex Rivera",
    closeDate: "2026-08-20",
  },
  {
    id: "deal_4",
    companyId: demoCompany.id,
    title: "Education onboarding",
    clientName: "BrightPath Schools",
    value: 18500,
    stage: "new",
    owner: "Jordan Lee",
    closeDate: "2026-09-01",
  },
  {
    id: "deal_5",
    companyId: demoCompany.id,
    title: "Warehouse ops pack",
    clientName: "Orbit Logistics",
    value: 32000,
    stage: "won",
    owner: "Sam Chen",
    closeDate: "2026-06-15",
  },
];

export const quotes: Quote[] = [
  {
    id: "qt_1",
    number: "Q-2026-014",
    clientId: "cli_1",
    clientName: "Nordic Facilities Inc.",
    status: "sent",
    total: 18400,
    currency: "CAD",
    issueDate: "2026-06-20",
    validUntil: "2026-07-20",
  },
  {
    id: "qt_2",
    number: "Q-2026-015",
    clientId: "cli_2",
    clientName: "Harbour Dental Group",
    status: "approved",
    total: 9200,
    currency: "CAD",
    issueDate: "2026-06-25",
    validUntil: "2026-07-25",
  },
  {
    id: "qt_3",
    number: "Q-2026-016",
    clientId: "cli_3",
    clientName: "Lumen Retail Partners",
    status: "draft",
    total: 5400,
    currency: "CAD",
    issueDate: "2026-07-03",
    validUntil: "2026-08-03",
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv_1",
    number: "INV-2026-088",
    clientId: "cli_1",
    clientName: "Nordic Facilities Inc.",
    status: "paid",
    total: 12400,
    currency: "CAD",
    issueDate: "2026-05-01",
    dueDate: "2026-05-31",
    paidAt: "2026-05-18",
  },
  {
    id: "inv_2",
    number: "INV-2026-094",
    clientId: "cli_2",
    clientName: "Harbour Dental Group",
    status: "pending",
    total: 4800,
    currency: "CAD",
    issueDate: "2026-06-15",
    dueDate: "2026-07-15",
  },
  {
    id: "inv_3",
    number: "INV-2026-097",
    clientId: "cli_1",
    clientName: "Nordic Facilities Inc.",
    status: "overdue",
    total: 7600,
    currency: "CAD",
    issueDate: "2026-05-20",
    dueDate: "2026-06-20",
  },
  {
    id: "inv_4",
    number: "INV-2026-101",
    clientId: "cli_4",
    clientName: "Cascade Builders",
    status: "sent",
    total: 15200,
    currency: "CAD",
    issueDate: "2026-07-01",
    dueDate: "2026-07-31",
  },
];

export const payments: Payment[] = [
  {
    id: "pay_1",
    invoiceNumber: "INV-2026-088",
    clientName: "Nordic Facilities Inc.",
    amount: 12400,
    currency: "CAD",
    status: "succeeded",
    method: "Stripe Checkout",
    createdAt: "2026-05-18",
  },
  {
    id: "pay_2",
    invoiceNumber: "SUB-GROWTH",
    clientName: "KlirBuild",
    amount: 149,
    currency: "CAD",
    status: "succeeded",
    method: "Subscription",
    createdAt: "2026-07-01",
  },
  {
    id: "pay_3",
    invoiceNumber: "INV-2026-094",
    clientName: "Harbour Dental Group",
    amount: 4800,
    currency: "CAD",
    status: "pending",
    method: "Stripe Checkout",
    createdAt: "2026-07-08",
  },
];

export const projects: Project[] = [
  {
    id: "prj_1",
    name: "Nordic onboarding",
    clientName: "Nordic Facilities Inc.",
    status: "active",
    progress: 68,
    members: ["AR", "SC", "JL"],
    dueDate: "2026-08-15",
    budget: 24000,
  },
  {
    id: "prj_2",
    name: "Dental multi-site rollout",
    clientName: "Harbour Dental Group",
    status: "active",
    progress: 42,
    members: ["SC", "AR"],
    dueDate: "2026-09-01",
    budget: 18000,
  },
  {
    id: "prj_3",
    name: "Retail pilot workspace",
    clientName: "Lumen Retail Partners",
    status: "planned",
    progress: 12,
    members: ["AR"],
    dueDate: "2026-09-20",
    budget: 9000,
  },
];

export const tasks: Task[] = [
  {
    id: "tsk_1",
    projectId: "prj_1",
    projectName: "Nordic onboarding",
    title: "Import historical invoices",
    status: "in_progress",
    priority: "high",
    assignee: "Sam Chen",
    dueDate: "2026-07-12",
  },
  {
    id: "tsk_2",
    projectId: "prj_1",
    projectName: "Nordic onboarding",
    title: "Configure approval workflow",
    status: "todo",
    priority: "medium",
    assignee: "Alex Rivera",
    dueDate: "2026-07-16",
  },
  {
    id: "tsk_3",
    projectId: "prj_2",
    projectName: "Dental multi-site rollout",
    title: "Train clinic managers",
    status: "review",
    priority: "high",
    assignee: "Jordan Lee",
    dueDate: "2026-07-14",
  },
  {
    id: "tsk_4",
    projectId: "prj_2",
    projectName: "Dental multi-site rollout",
    title: "Map room checklists",
    status: "done",
    priority: "medium",
    assignee: "Sam Chen",
    dueDate: "2026-07-05",
  },
  {
    id: "tsk_5",
    projectId: "prj_3",
    projectName: "Retail pilot workspace",
    title: "Draft pilot success criteria",
    status: "todo",
    priority: "low",
    assignee: "Alex Rivera",
    dueDate: "2026-07-18",
  },
];

export const documents: DocumentItem[] = [
  {
    id: "doc_1",
    name: "Master Service Agreement.pdf",
    folder: "Contracts",
    type: "pdf",
    size: "420 KB",
    updatedAt: "2026-06-12",
    tags: ["legal", "nordic"],
  },
  {
    id: "doc_2",
    name: "Q2 Revenue Summary.xlsx",
    folder: "Finance",
    type: "sheet",
    size: "188 KB",
    updatedAt: "2026-07-01",
    tags: ["finance"],
  },
  {
    id: "doc_3",
    name: "Site Kickoff Deck.pdf",
    folder: "Projects",
    type: "pdf",
    size: "2.1 MB",
    updatedAt: "2026-06-28",
    tags: ["onboarding"],
  },
  {
    id: "doc_4",
    name: "Clinic Floor Plan.png",
    folder: "Projects",
    type: "image",
    size: "960 KB",
    updatedAt: "2026-07-02",
    tags: ["dental"],
  },
];

export const automations: Automation[] = [
  {
    id: "auto_1",
    name: "Overdue invoice reminder",
    trigger: "Invoice overdue",
    active: true,
    runs: 128,
    lastRun: "2026-07-09",
  },
  {
    id: "auto_2",
    name: "New lead assignment",
    trigger: "Lead created",
    active: true,
    runs: 54,
    lastRun: "2026-07-08",
  },
  {
    id: "auto_3",
    name: "Quote approved → create project",
    trigger: "Quote approved",
    active: false,
    runs: 12,
    lastRun: "2026-06-22",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "act_1",
    type: "invoice",
    title: "Invoice INV-2026-097 marked overdue",
    description: "Nordic Facilities Inc. · $7,600",
    at: "2026-07-09T09:12:00",
  },
  {
    id: "act_2",
    type: "deal",
    title: "Deal moved to Negotiation",
    description: "Annual facilities OS",
    at: "2026-07-08T16:40:00",
  },
  {
    id: "act_3",
    type: "task",
    title: "Task completed",
    description: "Map room checklists",
    at: "2026-07-05T11:05:00",
  },
  {
    id: "act_4",
    type: "quote",
    title: "Quote approved",
    description: "Q-2026-015 · Harbour Dental Group",
    at: "2026-07-04T14:22:00",
  },
];

export const revenueSeries = [
  { month: "Jan", revenue: 42000 },
  { month: "Feb", revenue: 45500 },
  { month: "Mar", revenue: 51000 },
  { month: "Apr", revenue: 49800 },
  { month: "May", revenue: 56200 },
  { month: "Jun", revenue: 60100 },
  { month: "Jul", revenue: 58400 },
];

export const aiMessages: ChatMessage[] = [
  {
    id: "msg_1",
    role: "assistant",
    content:
      "Hi — I'm Klir AI. I can summarize overdue invoices, draft client follow-ups, create tasks, or give a weekly business snapshot.",
    at: "2026-07-09T10:00:00",
  },
];

export const suggestedPrompts = [
  "Summarize overdue invoices",
  "Draft a follow-up email for Nordic Facilities",
  "Create a task to prepare August invoices",
  "Give me this week's business summary",
];

export const kpi = {
  revenue: 58400,
  invoicesOpen: 3,
  clients: clients.length,
  projects: projects.filter((p) => p.status === "active").length,
  tasksDue: tasks.filter((t) => t.status !== "done").length,
  mrr: 149,
  pipeline: deals
    .filter((d) => !["won", "lost"].includes(d.stage))
    .reduce((sum, d) => sum + d.value, 0),
};
