/// <reference types="@cloudflare/workers-types" />
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv types/cloudflare-env.d.ts` (hash: c479e1e319486d05c56f08bc19ad3c4e)
interface __BaseEnv_CloudflareEnv {
	UPLOADS_BUCKET: R2Bucket;
	BACKUPS_BUCKET: R2Bucket;
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NEXT_PUBLIC_APP_URL: "https://klirline.app";
	UPLOADS_R2_ENABLED: "true";
	WORKER_SELF_REFERENCE: Service<typeof import("../workers/app").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/app");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_APP_URL" | "UPLOADS_R2_ENABLED">> {}
}
