/// <reference types="@cloudflare/workers-types" />
/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv types/cloudflare-env.d.ts` (hash: 24cfa2c7f3ee70e32f0ca268c70a7b88)
interface __BaseEnv_CloudflareEnv {
	UPLOADS_KV: KVNamespace;
	BACKUPS_KV: KVNamespace;
	NEXT_INC_CACHE_KV: KVNamespace;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
	NEXT_PUBLIC_APP_URL: "https://klirline.app";
	UPLOADS_KV_ENABLED: "true";
	WORKER_SELF_REFERENCE: Service<typeof import("../workers/app").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("../workers/app");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_APP_URL" | "UPLOADS_KV_ENABLED">> {}
}
