/** Catalogue plateformes — style Metricool / Connexions */
export type ZernioConnectionPlatform = {
  id: string;
  zernioKey: string;
  name: string;
  description: string;
  category: "social" | "ads" | "messaging";
  tileClass: string;
  monogram: string;
  /** Bouton CTA style Metricool */
  buttonBg: string;
  buttonText: string;
  iconBg: string;
  connectLabel: string;
  sidebar?: boolean;
};

export const ZERNIO_CONNECTION_PLATFORMS: ZernioConnectionPlatform[] = [
  {
    id: "facebook",
    zernioKey: "facebook",
    name: "Facebook",
    description: "Pages, publications et publicités Meta",
    category: "social",
    tileClass: "from-[#1877F2] to-[#0d5bb5]",
    monogram: "f",
    buttonBg: "bg-[#5b9fef]",
    buttonText: "text-white",
    iconBg: "bg-[#1877F2]",
    connectLabel: "Connecter une page Facebook",
    sidebar: true,
  },
  {
    id: "instagram",
    zernioKey: "instagram",
    name: "Instagram",
    description: "Posts, Stories, Reels et statistiques",
    category: "social",
    tileClass: "from-[#f58529] via-[#dd2a7b] to-[#8134af]",
    monogram: "IG",
    buttonBg: "bg-[#e84a8a]",
    buttonText: "text-white",
    iconBg: "bg-gradient-to-br from-[#f58529] via-[#dd2a7b] to-[#8134af]",
    connectLabel: "Connecter un compte professionnel Instagram",
    sidebar: true,
  },
  {
    id: "threads",
    zernioKey: "threads",
    name: "Threads",
    description: "Publications texte et médias",
    category: "social",
    tileClass: "from-[#101010] to-[#333333]",
    monogram: "@",
    buttonBg: "bg-[#1a1a1a]",
    buttonText: "text-white",
    iconBg: "bg-[#101010]",
    connectLabel: "Connecter un compte Threads",
  },
  {
    id: "twitter",
    zernioKey: "twitter",
    name: "X (Twitter)",
    description: "Posts et engagement",
    category: "social",
    tileClass: "from-[#14171A] to-[#000000]",
    monogram: "X",
    buttonBg: "bg-[#f3f0e6]",
    buttonText: "text-[#14171A]",
    iconBg: "bg-[#14171A]",
    connectLabel: "Connecter un compte Twitter / X",
  },
  {
    id: "bluesky",
    zernioKey: "bluesky",
    name: "Bluesky",
    description: "Réseau décentralisé",
    category: "social",
    tileClass: "from-[#0085ff] to-[#0066cc]",
    monogram: "B",
    buttonBg: "bg-[#7ec8ff]",
    buttonText: "text-[#003d73]",
    iconBg: "bg-[#0085ff]",
    connectLabel: "Connecter un compte Bluesky",
  },
  {
    id: "linkedin",
    zernioKey: "linkedin",
    name: "LinkedIn",
    description: "Page entreprise et posts professionnels",
    category: "social",
    tileClass: "from-[#0A66C2] to-[#004182]",
    monogram: "in",
    buttonBg: "bg-[#fff4c2]",
    buttonText: "text-[#5c4a00]",
    iconBg: "bg-[#0A66C2]",
    connectLabel: "Connecter LinkedIn",
    sidebar: true,
  },
  {
    id: "pinterest",
    zernioKey: "pinterest",
    name: "Pinterest",
    description: "Épingles et tableaux",
    category: "social",
    tileClass: "from-[#E60023] to-[#bd081c]",
    monogram: "P",
    buttonBg: "bg-[#e84d63]",
    buttonText: "text-white",
    iconBg: "bg-[#E60023]",
    connectLabel: "Connecter un compte Pinterest",
  },
  {
    id: "tiktok",
    zernioKey: "tiktok",
    name: "TikTok",
    description: "Vidéos courtes et analytics",
    category: "social",
    tileClass: "from-[#010101] to-[#25F4EE]",
    monogram: "TT",
    buttonBg: "bg-[#1a1a1a]",
    buttonText: "text-white",
    iconBg: "bg-[#010101]",
    connectLabel: "Connecter un compte TikTok business",
    sidebar: true,
  },
  {
    id: "google",
    zernioKey: "googlebusiness",
    name: "Google Business Profile",
    description: "Fiche locale et avis",
    category: "social",
    tileClass: "from-[#4285F4] via-[#34A853] to-[#FBBC05]",
    monogram: "G",
    buttonBg: "bg-[#5b9fef]",
    buttonText: "text-white",
    iconBg: "bg-[#4285F4]",
    connectLabel: "Connecter un compte Google Business Profile",
  },
  {
    id: "youtube",
    zernioKey: "youtube",
    name: "Youtube",
    description: "Chaîne, Shorts et planification",
    category: "social",
    tileClass: "from-[#FF0000] to-[#cc0000]",
    monogram: "YT",
    buttonBg: "bg-[#ff4d4d]",
    buttonText: "text-white",
    iconBg: "bg-[#FF0000]",
    connectLabel: "Connecter une chaîne YouTube",
    sidebar: true,
  },
  {
    id: "meta",
    zernioKey: "facebook",
    name: "Meta Ads",
    description: "Compte publicitaire et gestion Meta",
    category: "ads",
    tileClass: "from-[#0081FB] to-[#0064e0]",
    monogram: "M",
    buttonBg: "bg-[#5b9fef]",
    buttonText: "text-white",
    iconBg: "bg-[#0081FB]",
    connectLabel: "Connecter un compte Meta Ads",
  },
  {
    id: "reddit",
    zernioKey: "reddit",
    name: "Reddit",
    description: "Communautés et posts",
    category: "social",
    tileClass: "from-[#FF4500] to-[#ff6314]",
    monogram: "R",
    buttonBg: "bg-[#ff6b35]",
    buttonText: "text-white",
    iconBg: "bg-[#FF4500]",
    connectLabel: "Connecter un compte Reddit",
  },
  {
    id: "telegram",
    zernioKey: "telegram",
    name: "Telegram",
    description: "Canaux et messages",
    category: "messaging",
    tileClass: "from-[#2AABEE] to-[#229ED9]",
    monogram: "TG",
    buttonBg: "bg-[#5bc0f0]",
    buttonText: "text-white",
    iconBg: "bg-[#2AABEE]",
    connectLabel: "Connecter un canal Telegram",
  },
  {
    id: "whatsapp",
    zernioKey: "whatsapp",
    name: "WhatsApp",
    description: "Business et diffusion",
    category: "messaging",
    tileClass: "from-[#25D366] to-[#128C7E]",
    monogram: "WA",
    buttonBg: "bg-[#3ddc84]",
    buttonText: "text-white",
    iconBg: "bg-[#25D366]",
    connectLabel: "Connecter WhatsApp Business",
  },
  {
    id: "snapchat",
    zernioKey: "snapchat",
    name: "Snapchat",
    description: "Stories et profil public",
    category: "social",
    tileClass: "from-[#FFFC00] to-[#f5d300] text-black",
    monogram: "SC",
    buttonBg: "bg-[#fff44f]",
    buttonText: "text-[#1a1a00]",
    iconBg: "bg-[#FFFC00]",
    connectLabel: "Connecter un compte Snapchat",
  },
  {
    id: "discord",
    zernioKey: "discord",
    name: "Discord",
    description: "Serveurs et annonces",
    category: "messaging",
    tileClass: "from-[#5865F2] to-[#4752c4]",
    monogram: "D",
    buttonBg: "bg-[#7289da]",
    buttonText: "text-white",
    iconBg: "bg-[#5865F2]",
    connectLabel: "Connecter un serveur Discord",
  },
];

export function catalogPlatformById(id: string) {
  return ZERNIO_CONNECTION_PLATFORMS.find((p) => p.id === id);
}

export function catalogPlatformByZernioKey(key: string) {
  const k = key.toLowerCase();
  return (
    ZERNIO_CONNECTION_PLATFORMS.find((p) => p.zernioKey === k) ??
    ZERNIO_CONNECTION_PLATFORMS.find((p) => p.id === k)
  );
}
