import type { Category, Product } from './supabase';

export type DemoProduct = Product & { department: string };

export const DEMO_CATEGORIES: Category[] = [
  { id: 'cat-electronics', name: 'Electronics', slug: 'electronics', created_at: new Date().toISOString() },
  { id: 'cat-books', name: 'Books', slug: 'books', created_at: new Date().toISOString() },
  { id: 'cat-clothing', name: 'Clothing', slug: 'clothing', created_at: new Date().toISOString() },
  { id: 'cat-home', name: 'Home & Kitchen', slug: 'home-kitchen', created_at: new Date().toISOString() },
  { id: 'cat-sports', name: 'Sports', slug: 'sports', created_at: new Date().toISOString() },
  { id: 'cat-beauty', name: 'Beauty', slug: 'beauty', created_at: new Date().toISOString() },
  { id: 'cat-auto', name: 'Automotive', slug: 'automotive', created_at: new Date().toISOString() },
];

function product(partial: {
  id: string;
  name: string;
  description: string;
  price: number;
  original_price: number | null;
  image_url: string;
  category_id: string;
  department: string;
  seller_department: string;
  brand?: string;
  badge?: string | null;
  rating: number;
  review_count: number;
  deal_price?: number | null;
}): DemoProduct {
  return {
    deal_price: partial.deal_price ?? null,
    deal_ends_at: partial.deal_price ? new Date(Date.now() + 7 * 864e5).toISOString() : null,
    images: [partial.image_url],
    about_items: [],
    variants: [],
    seller_id: null,
    in_stock: true,
    featured: false,
    view_count: 0,
    brand: partial.brand ?? null,
    badge: partial.badge ?? null,
    seller_department: partial.seller_department,
    seller_verified: Boolean(partial.brand),
    seller_shop_name: partial.brand ?? null,
    created_at: new Date().toISOString(),
    id: partial.id,
    name: partial.name,
    description: partial.description,
    price: partial.price,
    original_price: partial.original_price,
    image_url: partial.image_url,
    category_id: partial.category_id,
    department: partial.department,
    rating: partial.rating,
    review_count: partial.review_count,
  };
}

/** Curated Haiti marketplace catalog (offline / fallback). */
export const DEMO_PRODUCTS: DemoProduct[] = [
  product({
    id: 'demo-solar',
    name: 'Lampe solaire portable LED',
    description: 'Éclairage rechargeable pour coupures — idéal maisons et commerces à Port-au-Prince.',
    price: 4500,
    original_price: 5800,
    image_url: 'https://images.pexels.com/photos/9875416/pexels-photo-9875416.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-electronics',
    department: 'Electronics',
    seller_department: 'Ouest',
    brand: 'Kay Solèy Énergie',
    rating: 4.7,
    review_count: 312,
    badge: 'best_seller',
  }),
  product({
    id: 'demo-powerbank',
    name: 'Power bank 20 000 mAh',
    description: 'Charge rapide USB-C pour smartphones — prêt pour les longues journées hors réseau.',
    price: 5500,
    original_price: 7200,
    deal_price: 4990,
    image_url: 'https://images.pexels.com/photos/5082579/pexels-photo-5082579.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-electronics',
    department: 'Electronics',
    seller_department: 'Ouest',
    brand: 'Tech Delmas Express',
    rating: 4.5,
    review_count: 891,
    badge: 'limited_deal',
  }),
  product({
    id: 'demo-water',
    name: 'Filtre à eau familial',
    description: 'Filtration gravitaire pour eau de citerne et robinet — jusqu’à 6 personnes.',
    price: 8900,
    original_price: 11000,
    image_url: 'https://images.pexels.com/photos/416528/pexels-photo-416528.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-home',
    department: 'Home & Kitchen',
    seller_department: 'Artibonite',
    brand: 'Aqua Klè',
    rating: 4.8,
    review_count: 204,
    badge: 'amazons_choice',
  }),
  product({
    id: 'demo-rice',
    name: 'Riz local 25 lb',
    description: 'Riz Haïti — sac familial prêt pour la cuisine du quotidien.',
    price: 3200,
    original_price: null,
    image_url: 'https://images.pexels.com/photos/4110255/pexels-photo-4110255.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-home',
    department: 'Home & Kitchen',
    seller_department: 'Artibonite',
    brand: 'Jaden Ayiti',
    rating: 4.6,
    review_count: 567,
  }),
  product({
    id: 'demo-coffee',
    name: 'Café moulu Lakay 500 g',
    description: 'Café torréfié artisanal — notes chocolatées, torréfaction sud Haïti.',
    price: 1500,
    original_price: 1800,
    image_url: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-home',
    department: 'Home & Kitchen',
    seller_department: 'Sud',
    brand: 'Café Lakay',
    rating: 4.9,
    review_count: 448,
    badge: 'best_seller',
  }),
  product({
    id: 'demo-carabela',
    name: 'Robe carabela brodée',
    description: 'Pièce artisanale Cap-Haïtien — coton léger, broderie traditionnelle.',
    price: 2800,
    original_price: 3500,
    image_url: 'https://images.pexels.com/photos/7679720/pexels-photo-7679720.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-clothing',
    department: 'Clothing & Fashion',
    seller_department: 'Nord',
    brand: 'Atelier Capois',
    rating: 4.4,
    review_count: 156,
    badge: 'new',
  }),
  product({
    id: 'demo-fan',
    name: 'Ventilateur rechargeable',
    description: 'Ventilateur USB/batterie pour chambres et boutiques pendant les coupures.',
    price: 3800,
    original_price: 4500,
    image_url: 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-home',
    department: 'Home & Kitchen',
    seller_department: 'Ouest',
    brand: 'Marché en Fer Select',
    rating: 4.3,
    review_count: 278,
  }),
  product({
    id: 'demo-helmet',
    name: 'Casque moto homologué',
    description: 'Protection pour moto-taxi et déplacements urbains — visière anti-UV.',
    price: 4200,
    original_price: 5200,
    image_url: 'https://images.pexels.com/photos/2116475/pexels-photo-2116475.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-auto',
    department: 'Automotive',
    seller_department: 'Ouest',
    brand: 'Motokask Sécurité',
    rating: 4.5,
    review_count: 190,
  }),
  product({
    id: 'demo-oil',
    name: 'Huile de ricin pure 100 ml',
    description: 'Soin cheveux et peau — production locale, flacon verre.',
    price: 850,
    original_price: null,
    image_url: 'https://images.pexels.com/photos/4041392/pexels-photo-4041392.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-beauty',
    department: 'Beauty & Personal Care',
    seller_department: 'Ouest',
    brand: 'Bèlte Lakay',
    rating: 4.7,
    review_count: 623,
    badge: 'best_seller',
  }),
  product({
    id: 'demo-ball',
    name: 'Ballon football taille 5',
    description: 'Ballon entraînement — terrains de Léogâne et clubs locaux.',
    price: 1800,
    original_price: 2200,
    image_url: 'https://images.pexels.com/photos/47730/the-ball-stadion-football-the-pitch-47730.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-sports',
    department: 'Sports & Outdoors',
    seller_department: 'Ouest',
    brand: 'Sport Léogâne',
    rating: 4.2,
    review_count: 98,
  }),
  product({
    id: 'demo-inverter',
    name: 'Onduleur 1000 W',
    description: 'Convertisseur 12 V → 110 V pour frigo et lumières en backup.',
    price: 18500,
    original_price: 22000,
    image_url: 'https://images.pexels.com/photos/257736/pexels-photo-257736.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-electronics',
    department: 'Electronics',
    seller_department: 'Sud-Est',
    brand: 'Énergie Soleil Jacmel',
    rating: 4.6,
    review_count: 134,
    badge: 'amazons_choice',
  }),
  product({
    id: 'demo-book-kreyol',
    name: 'Liv Kreyòl pou timoun',
    description: 'Album illustré bilingue FR/KR pour apprentis lecteurs.',
    price: 950,
    original_price: null,
    image_url: 'https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=800',
    category_id: 'cat-books',
    department: 'Books',
    seller_department: 'Ouest',
    brand: 'Libreri Lakay',
    rating: 4.8,
    review_count: 71,
    badge: 'new',
  }),
];
